name: Update Progress

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown-it-py

      - name: Update progress in README
        run: python scripts/update_progress.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "freeflowmc@mail.ru"
          git config --global user.name "korsajan"
          git add README.md
          git commit -m "Update progress" || exit 0
          git push